name: meubarbeiro

services:
  mysql:
    image: mysql:8.0
    container_name: meu-barbeiro-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_barbeiro_test
    ports:
      - "3307:3306"
    volumes:
      - meu_barbeiro_mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  meu_barbeiro_mysqldata:
